name: photo_share
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  uuid: ^4.2.2
  hooks_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.1.6
  image_picker: ^1.0.5
  image: ^4.1.3
  flutter_hooks: ^0.20.3
  collection: ^1.17.2
  intl: ^0.19.0
  video_thumbnail: ^0.5.3
  video_player: ^2.8.1
  lottie: ^2.7.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
